### ISSUE TITLE
Tạo module chưa loại bỏ thẻ đóng "?>" PHP

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-nvtools#1]

**Comment by htuyen1994** [comment]
chưa loại bỏ ở những file nào vậy a.

**Comment by hongoctrien** [comment]
Ở tất cả file đó em. Em kiểm tra lại bản trên vinades.org xem bỏ hết chưa.
Funcs mới tạo ý.

**Comment by htuyen1994** [comment]
E đã sửa rồi a nhé
