### ISSUE TITLE
Tạo module chưa tách menu ra file admin.menu.php

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-nvtools#3]

**Comment by htuyen1994** [comment]
với module nhỏ thì cần tách ra không a. tạo luôn trong admin_function cho đỡ gây nhiều file

**Comment by hongoctrien** [comment]
Cấu trúc module NukeViet 4 sẽ có thêm file admin.menu.php để chứa code menu, bỏ riêng ra đỡ rối hơn em.
